[package]
name = "kserve"
version = "1.0.0"
edition = "2024"

[dependencies]
actix-web = "4.14.0"
anyhow = "1.0.104"
comrak = "0.54.0"
mime_guess = "2.0.5"
serde = { version = "1.0.229", features = ["derive"] }
tokio = { version = "1.53.1", features = ["fs", "macros", "rt-multi-thread"] }
tokio-util = { version = "0.7.19", features = ["io"] }
toml = "1.1.3"
