[package]
name = "kserve"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.12.1"
anyhow = "1.0.100"
comrak = "0.48.0"
mime_guess = "2.0.5"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["fs", "macros", "rt-multi-thread"] }
tokio-util = { version = "0.7.17", features = ["io"] }
toml = "0.9.8"
