name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: move target
        run: if [ -d /opt/kserve/target ]; then mv /opt/kserve/target ./target; fi

      - name: release build
        run: |
          export PATH=/home/actions-runner/.cargo/bin:$PATH
          cargo build --release -p kserve

      - name: stop service
        id: stop_service
        run: sudo systemctl stop kserve

      - name: copy binary to run location
        run: cp ./target/release/kserve /opt/kserve

      - name: move target into cache
        run: mv ./target /opt/kserve/

      - name: restart service
        if: steps.stop_service.outcome == 'success'
        run: sudo systemctl restart kserve
